on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  snyk_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Snyk + snyk-to-html
        run: |
          npm install snyk-to-html -g

      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'synth'
          cdk_version: '2.40.0'
          working_dir: '.'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'

      - name: Run IaC for terraform
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          json: true

      - name: snyk to html
        run: |
          mkdir build
          snyk-to-html -i snyk.json -o build/results.html

      - name: snyk to html
        uses: actions/upload-artifact@v3
        with:
          name: vuln_report
          path: build/results.html


